### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jeffsaremi** [ConquestArrow/dtsmake#11]
Running the command like one of the following:

`dtsmake -s ./glsl-simulator-0.1.0.js --dist glsl-simulator -n "GLSL" -p node -l glsl-simulator.ts`

or 

`dtsmake -s ./glsl-simulator-0.1.0.js`

both produce this:
```

dtsmake started.
[CMD]node "C:\Users\jesaremi\AppData\Roaming\npm\node_modules\dtsmake\lib/../node_modules/tern/bin/condense" ./glsl-simulator-0.1.0.js --no-spans
[SRC]./glsl-simulator-0.1.0.js
C:\Users\jesaremi\AppData\Roaming\npm\node_modules\dtsmake\lib\dtsmake.js:493
                    at[at.length - 1] = nt;
                          ^

TypeError: Cannot read property 'length' of undefined
    at DTSMake.searchAndReplaceDTS (C:\Users\jesaremi\AppData\Roaming\npm\node_modules\dtsmake\lib\dtsmake.js:493:27)
    at DTSMake.preModifiedJson (C:\Users\jesaremi\AppData\Roaming\npm\node_modules\dtsmake\lib\dtsmake.js:186:26)
    at DTSMake.parseTernJson (C:\Users\jesaremi\AppData\Roaming\npm\node_modules\dtsmake\lib\dtsmake.js:119:26)
    at DTSMake.main (C:\Users\jesaremi\AppData\Roaming\npm\node_modules\dtsmake\lib\dtsmake.js:50:30)
    at C:\Users\jesaremi\AppData\Roaming\npm\node_modules\dtsmake\lib\index.js:154:16
    at ChildProcess.exithandler (child_process.js:282:7)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

**Comment by kikili** [comment]
I have exactly the same issue but with an other javascript file.
Did you manage to solve your issue ?
