### ISSUE TITLE
condense not found

### ISSUE THREAD

**Issue by Anchakor** [ConquestArrow/dtsmake#3]
Hi, I tried installing your tool, installed NPM, used the command `npm i dtsmake -g` but running it I get this error:

```
$ dtsmake -s libraries/plastiq.js 
v:3.9.6

dtsmake started.
[CMD]node "/home/anchakor/currentDirectory/node_modules/tern/bin/condense" libraries/plastiq.js --no-spans
[SRC]libraries/plastiq.js
[INFO] tern/condense error
Error: Command failed: node "/home/anchakor/currentDirectory/node_modules/tern/bin/condense" libraries/plastiq.js --no-spans
module.js:442
    throw err;
    ^

Error: Cannot find module '/home/anchakor/currentDirectory/node_modules/tern/bin/condense'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3
```

**Comment by CelsoSantos** [comment]
You'll have to install tern manually by using `npm install tern` (use the -g option if you feel it's suitable)

**Comment by walnutfalls** [comment]
+1

**Comment by genhirano** [comment]
+1

**Comment by intel352** [comment]
@CelsoSantos I have dtsmake and tern both installed globally. Error still occurs for me, seems dtsmake is looking for tern condense under local node_modules, rather than finding it in the global bin path?

**Comment by stevenqzhang** [comment]
Workaround is to add tern as a dev dependency:

`npm install --save-dev tern`

**Comment by nippur72** [comment]
I've installed `tern` as global and as `devDependencies`, but still get this error:

```
[CMD]node "C:\GitHub\Bravey\node_modules/tern/bin/condense" src --no-spans
[SRC]src
[INFO] tern/condense error
Error: Command failed: node "C:\GitHub\Bravey\node_modules/tern/bin/condense" src --no-spans
fs.js:675
  return binding.read(fd, buffer, offset, length, position);
                 ^

Error: EISDIR: illegal operation on a directory, read
```

**Comment by PeterGabriel2** [comment]
+1

**Comment by changzhn** [comment]
+10086

**Comment by df257** [comment]
> I've installed `tern` as global and as `devDependencies`, but still get this error:
> 
> ```
> [CMD]node "C:\GitHub\Bravey\node_modules/tern/bin/condense" src --no-spans
> [SRC]src
> [INFO] tern/condense error
> Error: Command failed: node "C:\GitHub\Bravey\node_modules/tern/bin/condense" src --no-spans
> fs.js:675
>   return binding.read(fd, buffer, offset, length, position);
>                  ^
> 
> Error: EISDIR: illegal operation on a directory, read
> ```

me too

**Comment by Delevin888** [comment]
> +10086

+10087

**Comment by yyman001** [comment]
+10088
